# Generated by Django 4.2 on 2023-04-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employe',
            new_name='is_employee',
        ),
    ]
